version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: psql
      POSTGRES_DB: pizza
    ports:
      - 5432:5432

  backend:
    build: src/backend
    command: npm start
    volumes:
      - ./src/backend:/backend
      - /backend/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000

  frontend:
    build: src/frontend
    command: npm run serve
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - '8080:8080'
    volumes:
      - ./src/frontend:/frontend
      - /frontend/node_modules
